name: Generate Sitemap

on:
  schedule:
    # - cron: "0 0 * * *"  # 매일 자정(UTC)에 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 필요한 라이브러리 설치
        run: pip install requests beautifulsoup4

      - name: 사이트맵 생성 스크립트 실행
        run: python generate_sitemap.py

      - name: 결과 파일 저장
        uses: actions/upload-artifact@v3
        with:
          name: sitemap
          path: sitemap-custom.xml
