name: Generate Sitemap

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 00:00(UTC 기준)에 실행 (한국 시간: 오전 9시)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 의존성 설치
        run: pip install requests

      - name: 사이트맵 생성 실행
        run: python generate_sitemap.py

      - name: 변경 사항 커밋
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "자동 생성된 사이트맵 업데이트" || echo "변경 사항 없음"
          git push
